#!/usr/bin/env node
/**
 * M2: GGD Token Generator
 * Reads all lawset JSON files, evaluates them via M1,
 * and produces ggd-tokens.css with CSS custom properties.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { evaluateLawset } from './evaluate-lawset.mjs';

// ── Path helpers (handle spaces in path) ─────────────────────────
const __filename = decodeURIComponent(new URL(import.meta.url).pathname);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '../..');
const LAWSETS_DIR = resolve(__dirname, '../equations/lawsets');
const OUTPUT_CSS = resolve(ROOT, 'site/src/styles/ggd-tokens.css');
const GLOBALS_CSS = resolve(ROOT, 'site/src/app/globals.css');

// ── Unit determination ───────────────────────────────────────────

/** Keys whose numeric values represent pixels */
const PX_KEY_PATTERNS = [
  'width', 'height', 'shell', 'pad', 'gutter', 'gap',
  '_x', 'band', 'row', 'col_w', 'span',
];

/** Keys whose numeric values are unitless ratios */
const UNITLESS_KEY_PATTERNS = [
  'ratio', 'aspect', 'delta',
];

/** Typography derived keys that get px */
const TYPO_PX_KEYS = ['display', 'section_title', 'eyebrow', 'mobile_display', 'body_base'];

function getUnit(key, value, lawsetId) {
  // String values starting with # are colors
  if (typeof value === 'string' && value.startsWith('#')) return '';
  // Non-numeric values get no unit
  if (typeof value !== 'number') return '';

  // Typography scale values get px
  if (lawsetId === 'typography.scale' && TYPO_PX_KEYS.includes(key)) return 'px';

  // Unitless ratio keys
  if (UNITLESS_KEY_PATTERNS.some(p => key.includes(p))) return '';

  // Known px keys: u and h are base units in px
  if (key === 'u' || key === 'h') return 'px';

  // Pixel keys by pattern
  if (PX_KEY_PATTERNS.some(p => key.includes(p))) return 'px';

  // Color contrast derived values (contrast ratios) are unitless
  if (lawsetId === 'color.contrast' && key.includes('on_surface')) return '';
  if (lawsetId === 'color.contrast' && key === 'surface_delta') return '';

  // Default: unitless for remaining numbers
  return '';
}

// ── Kebab-case conversion ────────────────────────────────────────

function toKebab(str) {
  return str
    .replace(/\./g, '-')     // dots to hyphens
    .replace(/_/g, '-');      // underscores to hyphens
}

// ── Typography role mapping ──────────────────────────────────────

const TYPO_ROLE_MAP = {
  'display': 'type-display',
  'section_title': 'type-section-title',
  'eyebrow': 'type-eyebrow',
  'body_base': 'type-body-base',
  'mobile_display': 'type-mobile-display',
  'desktop_ratio': 'type-desktop-ratio',
  'mobile_ratio': 'type-mobile-ratio',
};

// ── Color token mapping ──────────────────────────────────────────

const COLOR_TOKEN_MAP = {
  'surface': 'color-surface',
  'surface_raised': 'color-surface-raised',
  'text_primary': 'color-text-primary',
  'text_secondary': 'color-text-secondary',
  'emphasis': 'color-emphasis',
  'warning': 'color-warning',
  'fail': 'color-fail',
};

// ── Shared constants ─────────────────────────────────────────────

const SHARED_TOKENS = [
  ['--ggd-unit', '8px'],
  ['--ggd-half-unit', '4px'],
  ['--ggd-cols-desktop', '16'],
  ['--ggd-cols-tablet', '10'],
  ['--ggd-cols-mobile', '6'],
  ['--ggd-gutter-desktop', '24px'],
  ['--ggd-gutter-tablet', '24px'],
  ['--ggd-gutter-mobile', '16px'],
];

// ── Format value ─────────────────────────────────────────────────

function formatValue(value, unit) {
  if (typeof value === 'string') return value;
  if (typeof value === 'number') {
    // Round to avoid floating point noise
    const rounded = Math.round(value * 100) / 100;
    return `${rounded}${unit}`;
  }
  return String(value);
}

// ── Main ─────────────────────────────────────────────────────────

function generate() {
  const lawsetFiles = readdirSync(LAWSETS_DIR).filter(f => f.endsWith('.json'));
  const lines = [];
  let tokenCount = 0;

  lines.push('/* GGD Design Tokens — auto-generated by generate-tokens.mjs */');
  lines.push('/* Do not edit manually. Regenerate with: node GGD/scripts/generate-tokens.mjs */');
  lines.push('');
  lines.push(':root {');

  // ── Shared constants ──
  lines.push('  /* Shared constants */');
  for (const [name, value] of SHARED_TOKENS) {
    lines.push(`  ${name}: ${value};`);
    tokenCount++;
  }
  lines.push('');

  // ── Evaluate each lawset ──
  for (const file of lawsetFiles.sort()) {
    const filePath = resolve(LAWSETS_DIR, file);
    const result = evaluateLawset(filePath);
    const lawsetId = result.id;
    const prefix = toKebab(lawsetId);

    // Decide which naming strategy to use
    const isTypography = lawsetId === 'typography.scale';
    const isColor = lawsetId === 'color.contrast';

    lines.push(`  /* ${lawsetId} */`);

    // Constants
    for (const [key, value] of Object.entries(result.constants)) {
      let tokenName;
      if (isTypography && TYPO_ROLE_MAP[key]) {
        tokenName = `--ggd-${TYPO_ROLE_MAP[key]}`;
      } else if (isColor && COLOR_TOKEN_MAP[key]) {
        tokenName = `--ggd-${COLOR_TOKEN_MAP[key]}`;
      } else {
        tokenName = `--ggd-${prefix}-${toKebab(key)}`;
      }

      const unit = getUnit(key, value, lawsetId);
      lines.push(`  ${tokenName}: ${formatValue(value, unit)};`);
      tokenCount++;
    }

    // Derived values
    for (const [key, value] of Object.entries(result.derived_values)) {
      // Skip error values
      if (value && typeof value === 'object' && value.error) {
        process.stderr.write(`  WARN: skipping ${lawsetId}.${key}: ${value.error}\n`);
        continue;
      }

      let tokenName;
      if (isTypography && TYPO_ROLE_MAP[key]) {
        tokenName = `--ggd-${TYPO_ROLE_MAP[key]}`;
      } else if (isColor) {
        // Derived color values are contrast ratios — use descriptive names
        tokenName = `--ggd-color-${toKebab(key)}`;
      } else {
        tokenName = `--ggd-${prefix}-${toKebab(key)}`;
      }

      const unit = getUnit(key, value, lawsetId);
      lines.push(`  ${tokenName}: ${formatValue(value, unit)};`);
      tokenCount++;
    }

    lines.push('');
  }

  lines.push('}');
  lines.push('');

  // ── Responsive breakpoint tokens ──
  // Tablet lawsets → @media (max-width: 1023px)
  // Mobile lawsets → @media (max-width: 767px)
  const breakpointMap = {
    tablet: { query: '@media (max-width: 1023px)', lawsets: [] },
    mobile: { query: '@media (max-width: 767px)', lawsets: [] },
  };

  for (const file of lawsetFiles.sort()) {
    const filePath = resolve(LAWSETS_DIR, file);
    const result = evaluateLawset(filePath);
    const id = result.id;
    if (id.includes('.tablet.')) breakpointMap.tablet.lawsets.push({ file, result });
    else if (id.includes('.mobile.')) breakpointMap.mobile.lawsets.push({ file, result });
  }

  for (const [bp, { query, lawsets }] of Object.entries(breakpointMap)) {
    if (lawsets.length === 0) continue;
    lines.push(`/* Responsive: ${bp} */`);
    lines.push(`${query} {`);
    lines.push('  :root {');

    // Shared column/gutter overrides
    if (bp === 'tablet') {
      lines.push(`    --ggd-cols: 10;`);
      lines.push(`    --ggd-gutter: 24px;`);
    } else if (bp === 'mobile') {
      lines.push(`    --ggd-cols: 6;`);
      lines.push(`    --ggd-gutter: 16px;`);
    }

    for (const { result } of lawsets) {
      const lawsetId = result.id;
      const prefix = toKebab(lawsetId);
      const isTypoMobile = lawsetId.startsWith('typography.scale.mobile');

      lines.push(`    /* ${lawsetId} */`);

      // Key derived values that override desktop
      const allValues = { ...result.constants, ...result.derived_values };
      for (const [key, value] of Object.entries(allValues)) {
        if (value && typeof value === 'object' && value.error) continue;

        let tokenName;
        if (isTypoMobile && TYPO_ROLE_MAP[key]) {
          tokenName = `--ggd-${TYPO_ROLE_MAP[key]}`;
        } else {
          tokenName = `--ggd-${prefix}-${toKebab(key)}`;
        }

        const unit = getUnit(key, value, lawsetId);
        lines.push(`    ${tokenName}: ${formatValue(value, unit)};`);
        tokenCount++;
      }

      // Also emit a short-name page-shell override for responsive use
      if (allValues.page_shell !== undefined) {
        lines.push(`    --ggd-page-shell: ${allValues.page_shell}px;`);
        tokenCount++;
      }
    }

    lines.push('  }');
    lines.push('}');
    lines.push('');
  }

  // Write CSS
  const css = lines.join('\n');
  writeFileSync(OUTPUT_CSS, css, 'utf-8');

  // ── Update globals.css ──
  if (existsSync(GLOBALS_CSS)) {
    let globals = readFileSync(GLOBALS_CSS, 'utf-8');
    let changed = false;

    // Add import at the very top if not already present
    const importLine = "@import '../styles/ggd-tokens.css';";
    if (!globals.includes(importLine)) {
      globals = importLine + '\n\n' + globals;
      changed = true;
    }

    // Replace --grid-max: 984px
    const gridMaxRe = /--grid-max:\s*984px/;
    if (gridMaxRe.test(globals)) {
      globals = globals.replace(gridMaxRe, '--grid-max: var(--ggd-home-desktop-shell-page-shell)');
      changed = true;
    }

    // Replace --grid-pad: 20px
    const gridPadRe = /--grid-pad:\s*20px/;
    if (gridPadRe.test(globals)) {
      globals = globals.replace(gridPadRe, '--grid-pad: var(--ggd-home-desktop-shell-page-pad)');
      changed = true;
    }

    if (changed) {
      writeFileSync(GLOBALS_CSS, globals, 'utf-8');
      process.stderr.write(`Updated globals.css with GGD token references.\n`);
    }
  }

  process.stderr.write(`Generated ${tokenCount} tokens in ${OUTPUT_CSS}\n`);
  return tokenCount;
}

generate();
